name: CI

on:
  push:
  pull_request:
  repository_dispatch:
    types: [run_build]
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ${{ matrix.os[0] }}
    strategy:
      matrix:
        os: [
          [windows-latest, x86_64, msys2]
        ]
      fail-fast: false
    defaults:
     run:
      shell: ${{ matrix.os[2] }} {0}

    steps:
    - uses: actions/checkout@v4

    - name: Install Ubuntu packages
      if: matrix.os[0] == 'ubuntu-latest'
      run: |
        sudo apt-get update
        sudo apt-get -y install texinfo bison flex gettext autopoint autoconf automake libgmp3-dev libmpfr-dev libmpc-dev

    - name: Install macOS packages
      if: startsWith(matrix.os[0], 'macos')
      run: |
        brew update
        brew install texinfo bison flex gnu-sed autoconf automake libtool gsl gmp mpfr libmpc md5sha1sum

    - name: Install MSYS2 packages
      if: matrix.os[0] == 'windows-latest'
      uses: msys2/setup-msys2@v2
      with:
        msystem: MINGW32
        install: |
          base-devel git make texinfo flex bison patch binutils mingw-w64-i686-gcc mpc-devel tar
          autotools gettext gettext-devel python3 python3-pip ncurses-devel diffutils
          mingw-w64-i686-cmake mingw-w64-i686-make mingw-w64-i686-libogg
        update: true

    - name: Runs all the stages in the shell
      run: |
        export PATH="$(brew --prefix gnu-sed)/libexec/gnubin:$PATH" # This really is only needed for macOS
        export PATH="$(brew --prefix libtool)/libexec/gnubin:$PATH" # This really is only needed for macOS
        export PKG_CONFIG_PATH="$(brew --prefix libarchive)/lib/pkgconfig:$(brew --prefix openssl)/lib/pkgconfig" #This really is only needed for macOS
        export PSPDEV=$PWD/pspdev
        export PATH=$PATH:$PSPDEV/bin
        ./build-all.sh

    - name: Get short SHA
      id: slug
      run: echo "sha8=${MSYSTEM}-sha[$(echo ${GITHUB_SHA} | cut -c1-8)" >> $GITHUB_OUTPUT

    - name: Prepare pspdev folder
      run: |
        tar -zcvf pspdev-${{matrix.os[0]}}-${{matrix.os[1]}}.tar.gz pspdev

    - uses: actions/upload-artifact@v4
      with:
        name: pspdev-${{matrix.os[0]}}-${{matrix.os[1]}}
        path: pspdev-${{matrix.os[0]}}-${{matrix.os[1]}}.tar.gz

